use_frameworks!

platform :ios, '8.0'

target 'HSYUIArchitectureToolsKit_Example' do
  pod 'HSYUIArchitectureToolsKit', :path => '../'

  target 'HSYUIArchitectureToolsKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
